# Generated by Django 5.2.4 on 2025-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('NO_of_guests', models.IntegerField()),
                ('BookingDate', models.DateField()),
                ('BookingTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Inventory', models.IntegerField()),
            ],
        ),
    ]
