# Generated by Django 6.0.5 on 2026-05-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
